=== kardos24/ARSOFinal/xml/ejercicio1-2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/ejercicio1-2"
	xmlns:tns="http://www.example.org/ejercicio1-2" elementFormDefault="qualified">

	<simpleType name="tipo_url">
		<restriction base="string">
			<pattern value="(https?://)?(.+\.)*.+(/.*)?" />
		</restriction>
	</simpleType>

	<simpleType name="tipo_hora">
		<restriction base="string">
			<pattern value="[0-9][0-9]+:[0-5][0-9]:[0-5][0-9]" />
		</restriction>
	</simpleType>

	<element name="programas">
		<complexType>
			<sequence>
				<element name="programa">
					<complexType>
						<sequence>
							<element name="nombre" type="string" />
							<element name="url-programa" type="anyURI" />
							<element name="url-portada" type="anyURI" />
							<element name="emision" minOccurs="1" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="titulo" type="string" />
										<element name="fecha" type="date" />
										<element name="tiempo-emision" type="tns:tipo_hora" />
										<element name="url-emision" type="tns:tipo_url" />
									</sequence>
								</complexType>
							</element>
						</sequence>
						<attribute name="identificador" type="string" use="required" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>

</schema>

=== kardos24/ARSOFinal/xml/ejercicio1-2.xml
<?xml version="1.0" encoding="UTF-8"?>

<programa identificador="acacias-38" xmlns="http://www.example.org/ejercicio1-2"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ejercicio1-2 ejercicio1-2.xsd ">
	<nombre>Acacias 38</nombre>
	<url-programa>http://www.rtve.es/m/alacarta/videos/acacias-38/?media=tve</url-programa>
	<url-portada>http://img.rtve.es/imagenes/acacias-38/1425305370705.png</url-portada>
	<emision>
		<titulo>Capítulo 447</titulo>
		<fecha>2017-02-03</fecha>
		<tiempo-emision>00:54:44</tiempo-emision>
		<url-emision>http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-447/3898958/?media=tve</url-emision>
	</emision>
	<emision>
		<titulo>Capítulo 446</titulo>
		<fecha>2017-02-02</fecha>
		<tiempo-emision>00:55:50</tiempo-emision>
		<url-emision>http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-446/3897001/?media=tve</url-emision>
	</emision>
</programa>

=== kardos24/ARSOFinal/xml-bd/ejercicio1-2.xml
<?xml version="1.0" encoding="UTF-8"?>

<e:programa identificador="acacias-38"
	xmlns:e="http://www.example.org/ejercicio1-2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ejercicio1-2 ejercicio1-2.xsd ">
	<e:nombre>Acacias 38</e:nombre>
	<e:url-programa>
		http://www.rtve.es/m/alacarta/videos/acacias-38/?media=tve</e:url-programa>
	<e:url-portada>
		http://img.rtve.es/imagenes/acacias-38/1425305370705.png</e:url-portada>
	<e:emision>
		<e:titulo>
			Capítulo 447
		</e:titulo>
		<e:fecha>2017-02-03</e:fecha>
		<e:tiempo-emision>
			00:54:44
		</e:tiempo-emision>
		<e:url-emision>
			http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-447/3898958/?media=tve</e:url-emision>
	</e:emision>
	<e:emision>
		<e:titulo>
			Capítulo 446
		</e:titulo>
		<e:fecha>2017-02-02</e:fecha>
		<e:tiempo-emision>
			00:55:50
		</e:tiempo-emision>
		<e:url-emision>
			http://www.rtve.es/m/alacarta/videos/acacias-38/acacias-38-capitulo-446/3897001/?media=tve</e:url-emision>
	</e:emision>
</e:programa>
