=== kardos24/ARSOFinal/xml/ejercicio2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/ejercicio2"
	xmlns:tns="http://www.example.org/ejercicio2" elementFormDefault="qualified">

	<simpleType name="tipo_hora">
		<restriction base="string">
			<pattern value="(\d+:)?[0-5]\d:[0-5]\d" />
		</restriction>
	</simpleType>

	<complexType name="tipo_programa">
		<sequence>
			<element name="nombre" type="string" />
			<element name="url-programa" type="anyURI" />
			<element name="url-portada" type="anyURI" />
			<element name="emision" minOccurs="1" maxOccurs="unbounded"
				type="tns:tipo_emision" />
		</sequence>
		<attribute name="identificador" type="string" use="required" />
	</complexType>

	<complexType name="tipo_emision">
		<sequence>
			<element name="titulo" type="string" />
			<element name="fecha" type="date" />
			<element name="tiempo-emision" type="tns:tipo_hora" />
			<element name="url-emision" type="anyURI" />
		</sequence>
	</complexType>

	<element name="programa" type="tns:tipo_programa" />
</schema>

=== kardos24/ARSOFinal/xml-bd/alaska-y-segura.xml
<?xml version="1.0" ?><programa xmlns="http://www.example.org/ejercicio2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio2 ejercicio2.xsd" identificador="alaska-y-segura"><nombre>Alaska y Segura</nombre><url-programa>/m/alacarta/videos/alaska-y-segura/?media=tve</url-programa><url-portada>http://img.rtve.es/imagenes/alaska-segura/1423649639233.png</url-portada><emision><titulo>Viva Buñuel</titulo><fecha>2015-05-25</fecha><tiempo-emision>1:41:03</tiempo-emision><url-emision>/m/alacarta/videos/alaska-y-segura/alaska-segura-viva-bunuel/3141222/?media=tve</url-emision></emision><emision><titulo>Danzad malditos</titulo><fecha>2015-05-18</fecha><tiempo-emision>1:22:34</tiempo-emision><url-emision>/m/alacarta/videos/alaska-y-segura/alaska-segura-danzad-malditos/3132849/?media=tve</url-emision></emision><emision><titulo>La primera vez</titulo><fecha>2015-05-11</fecha><tiempo-emision>1:41:01</tiempo-emision><url-emision>/m/alacarta/videos/alaska-y-segura/alaska-segura-primera-vez/3124180/?media=tve</url-emision></emision><emision><titulo>La noche de los muertos vivientes</titulo><fecha>2015-05-04</fecha><tiempo-emision>1:25:01</tiempo-emision><url-emision>/m/alacarta/videos/alaska-y-segura/alaska-segura-noche-muertos-vivientes/3115898/?media=tve</url-emision></emision><emision><titulo>La bola de cristal</titulo><fecha>2015-04-20</fecha><tiempo-emision>1:41:43</tiempo-emision><url-emision>/m/alacarta/videos/alaska-y-segura/alaska-segura-bola-cristal/3099462/?media=tve</url-emision></emision><emision><titulo>La ley de la calle</titulo><fecha>2015-04-13</fecha><tiempo-emision>1:18:59</tiempo-emision><url-emision>/m/alacarta/videos/alaska-y-segura/alaska-segura-ley-calle/3089328/?media=tve</url-emision></emision><emision><titulo>Fan fatal</titulo><fecha>2015-04-06</fecha><tiempo-emision>1:14:49</tiempo-emision><url-emision>/m/alacarta/videos/alaska-y-segura/alaska-segura-fan-fatal/3077898/?media=tve</url-emision></emision><emision><titulo>Karaoke Kid</titulo><fecha>2015-03-30</fecha><tiempo-emision>1:18:55</tiempo-emision><url-emision>/m/alacarta/videos/alaska-y-segura/alaska-segura-karaoke-kid/3069819/?media=tve</url-emision></emision></programa>

=== kardos24/ARSOFinal/xml-bd/amar-en-tiempos-revueltos.xml
<?xml version="1.0" ?>
<programa xmlns="http://www.example.org/ejercicio2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ejercicio2 ejercicio2.xsd"
	identificador="amar-en-tiempos-revueltos">
	<nombre>Amar en tiempos revueltos</nombre>
	<url-programa>/m/alacarta/videos/amar-en-tiempos-revueltos/?media=tve
	</url-programa>
	<url-portada>http://img.rtve.es/imagenes/amar-tiempos-revueltos/1488798760813.png
	</url-portada>
	<emision>
		<titulo>T7 - Cap�tulo 256 - Final 2� Parte</titulo>
		<fecha>2012-11-16</fecha>
		<tiempo-emision>56:12</tiempo-emision>
		<url-emision>/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-256-final-2-parte/1580482/?media=tve
		</url-emision>
	</emision>
	<emision>
		<titulo>T7 - Cap�tulo 255 - Final 1� parte</titulo>
		<fecha>2012-11-16</fecha>
		<tiempo-emision>54:55</tiempo-emision>
		<url-emision>/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-255-final-1-parte/1580102/?media=tve
		</url-emision>
	</emision>
	<emision>
		<titulo>T7 - Cap�tulo 254</titulo>
		<fecha>2012-11-15</fecha>
		<tiempo-emision>54:42</tiempo-emision>
		<url-emision>/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-254/1580324/?media=tve
		</url-emision>
	</emision>
	<emision>
		<titulo>T7 - Cap�tulo 253</titulo>
		<fecha>2012-11-13</fecha>
		<tiempo-emision>55:10</tiempo-emision>
		<url-emision>/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-253/1578684/?media=tve
		</url-emision>
	</emision>
	<emision>
		<titulo>T7 - Cap�tulo 252</titulo>
		<fecha>2012-11-12</fecha>
		<tiempo-emision>54:03</tiempo-emision>
		<url-emision>/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-252/1577813/?media=tve
		</url-emision>
	</emision>
	<emision>
		<titulo>T7 - Cap�tulo 251</titulo>
		<fecha>2012-11-09</fecha>
		<tiempo-emision>54:26</tiempo-emision>
		<url-emision>/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-251/1574546/?media=tve
		</url-emision>
	</emision>
	<emision>
		<titulo>T7 - Cap�tulo 250</titulo>
		<fecha>2012-11-08</fecha>
		<tiempo-emision>54:44</tiempo-emision>
		<url-emision>/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-250/1574547/?media=tve
		</url-emision>
	</emision>
	<emision>
		<titulo>T7 - Cap�tulo 249</titulo>
		<fecha>2012-11-07</fecha>
		<tiempo-emision>54:50</tiempo-emision>
		<url-emision>/m/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t7-capitulo-249/1573352/?media=tve
		</url-emision>
	</emision>
</programa>

=== kardos24/ARSOFinal/xml-bd/aguila-roja.xml
<?xml version="1.0" ?><programa xmlns="http://www.example.org/ejercicio2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ejercicio2 ejercicio2.xsd" identificador="aguila-roja"><nombre>Águila Roja</nombre><url-programa>/m/alacarta/videos/aguila-roja/?media=tve</url-programa><url-portada>http://img.rtve.es/imagenes/aguila-roja/1412769760573.png</url-portada><emision><titulo>T9 - Capítulo 116</titulo><fecha>2016-10-27</fecha><tiempo-emision>1:27:40</tiempo-emision><url-emision>/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-116/3771566/?media=tve</url-emision></emision><emision><titulo>T9 - Capítulo 115</titulo><fecha>2016-10-20</fecha><tiempo-emision>1:21:25</tiempo-emision><url-emision>/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-115/3763280/?media=tve</url-emision></emision><emision><titulo>T9 - Capítulo 114</titulo><fecha>2016-10-13</fecha><tiempo-emision>1:16:39</tiempo-emision><url-emision>/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-114/3752919/?media=tve</url-emision></emision><emision><titulo>T9 - Capítulo 113</titulo><fecha>2016-10-06</fecha><tiempo-emision>1:18:45</tiempo-emision><url-emision>/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-113/3745187/?media=tve</url-emision></emision><emision><titulo>T9 - Capítulo 112</titulo><fecha>2016-09-29</fecha><tiempo-emision>1:18:43</tiempo-emision><url-emision>/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-112/3736718/?media=tve</url-emision></emision><emision><titulo>T9 - Capítulo 111</titulo><fecha>2016-09-22</fecha><tiempo-emision>1:19:10</tiempo-emision><url-emision>/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-111/3728076/?media=tve</url-emision></emision><emision><titulo>T9 - Capítulo 110</titulo><fecha>2016-09-15</fecha><tiempo-emision>1:18:11</tiempo-emision><url-emision>/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-110/3719743/?media=tve</url-emision></emision><emision><titulo>T9 - Capítulo 109</titulo><fecha>2016-07-19</fecha><tiempo-emision>1:19:07</tiempo-emision><url-emision>/m/alacarta/videos/aguila-roja/aguila-roja-t9-capitulo-109/3664155/?media=tve</url-emision></emision></programa>
